@startuml
package App as App {
  entity User {
    * id : UUID
    --
    * email : String
    * name : String
    created_at : DateTime
  }

  entity Post {
    * id : UUID
    --
    * title : String
    * category_id : UUID
    * content : Text
    * user_id : UUID <<FK>>
    published_at : DateTime
  }

  entity Comment {
    * id : UUID
    --
    * content : Text
    * user_id : UUID <<FK>>
    * post_id : UUID <<FK>>
    created_at : DateTime
  }

  User ||--o{ Post : "creates"
  User ||--o{ Comment : "writes"
  Post ||--o{ Comment : "has"
}
@enduml
